# Generated by Django 2.0.4 on 2018-04-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
                'indexes': [],
            },
            bases=('courses.course',),
        ),
    ]
